import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
      {
          "name": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
          "price": 109.95,
          "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
          "category": "men's clothing",
          "image": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
          "rating": 3.9,
          "count": 120,
          numReviews: 2,
          countInStock: 3,
          brand: 'Fjallraven',
      },
      {
          "name": "Mens Casual Premium Slim Fit T-Shirts ",
          "price": 22.3,
          "description": "Slim-fitting style, contrast raglan long sleeve, three-button henley placket, light weight & soft fabric for breathable and comfortable wearing. And Solid stitched shirts with round neck made for durability and a great fit for casual fashion wear and diehard baseball fans. The Henley style round neckline includes a three-button placket.",
          "category": "men's clothing",
          "image": "https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg",
          "rating":4.1,
          "count": 259
      },
      {
          "id": 3,
          "name": "Mens Cotton Jacket",
          "price": 55.99,
          "description": "great outerwear jackets for Spring/Autumn/Winter, suitable for many occasions, such as working, hiking, camping, mountain/rock climbing, cycling, traveling or other outdoors. Good gift choice for you or your family member. A warm hearted love to Father, husband or son in this thanksgiving or Christmas Day.",
          "category": "men's clothing",
          "image": "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
          "rating":4.7,
          "count": 500
      },
      {
          "id": 4,
          "name": "Mens Casual Slim Fit",
          "price": 15.99,
          "description": "The color could be slightly different between on the screen and in practice. / Please note that body builds vary by person, therefore, detailed size information should be reviewed below on the product description.",
          "category": "men's clothing",
          "image": "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
          "rating": 2.1,
          "count": 430
      },
      {
          "id": 5,
          "name": "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
          "price": 695,
          "description": "From our Legends Collection, the Naga was inspired by the mythical water dragon that protects the ocean's pearl. Wear facing inward to be bestowed with love and abundance, or outward for protection.",
          "category": "jewelery",
          "image": "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
          "rating": 4.6,
          "count": 400
      },
      {
          "id": 6,
          "name": "Solid Gold Petite Micropave ",
          "price": 168,
          "description": "Satisfaction Guaranteed. Return or exchange any order within 30 days.Designed and sold by Hafeez Center in the United States. Satisfaction Guaranteed. Return or exchange any order within 30 days.",
          "category": "jewelery",
          "image": "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
          "rating": 3.9,
          "count": 70
      },
      {
          "id": 7,
          "name": "White Gold Plated Princess",
          "price": 9.99,
          "description": "Classic Created Wedding Engagement Solitaire Diamond Promise Ring for Her. Gifts to spoil your love more for Engagement, Wedding, Anniversary, Valentine's Day...",
          "category": "jewelery",
          "image": "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
          "rating": 3,
          "count": 400
      },
      {
          "id": 8,
          "name": "Pierced Owl Rose Gold Plated Stainless Steel Double",
          "price": 10.99,
          "description": "Rose Gold Plated Double Flared Tunnel Plug Earrings. Made of 316L Stainless Steel",
          "category": "jewelery",
          "image": "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
          "rating": 1.9,
          "count": 100
      },
      {
          "id": 9,
          "name": "WD 2TB Elements Portable External Hard Drive - USB 3.0 ",
          "price": 64,
          "description": "USB 3.0 and USB 2.0 Compatibility Fast data transfers Improve PC Performance High Capacity; Compatibility Formatted NTFS for Windows 10, Windows 8.1, Windows 7; Reformatting may be required for other operating systems; Compatibility may vary depending on user’s hardware configuration and operating system",
          "category": "electronics",
          "image": "https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg",
          "rating":3.3,
          "count": 203
      },
      {
          "id": 10,
          "name": "SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s",
          "price": 109,
          "description": "Easy upgrade for faster boot up, shutdown, application load and response (As compared to 5400 RPM SATA 2.5” hard drive; Based on published specifications and internal benchmarking tests using PCMark vantage scores) Boosts burst write performance, making it ideal for typical PC workloads The perfect balance of performance and reliability Read/write speeds of up to 535MB/s/450MB/s (Based on internal testing; Performance may vary depending upon drive capacity, host device, OS and application.)",
          "category": "electronics",
          "image": "https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg",
          "rating": 2.9,
          "count": 470
      },
      {
          "id": 11,
          "name": "Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5",
          "price": 109,
          "description": "3D NAND flash are applied to deliver high transfer speeds Remarkable transfer speeds that enable faster bootup and improved overall system performance. The advanced SLC Cache Technology allows performance boost and longer lifespan 7mm slim design suitable for Ultrabooks and Ultra-slim notebooks. Supports TRIM command, Garbage Collection technology, RAid, and ECC (Error Checking & Correction) to provide the optimized performance and enhanced reliability.",
          "category": "electronics",
          "image": "https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg",
          "rating": 4.8,
          "count": 319
      },
      {
          "id": 12,
          "name": "WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive",
          "price": 114,
          "description": "Expand your PS4 gaming experience, Play anywhere Fast and easy, setup Sleek design with high capacity, 3-year brand's limited warranty",
          "category": "electronics",
          "image": "https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg",
          "rating":4.8,
          "count": 400
      },
      {
          "id": 13,
          "name": "Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin",
          "price": 599,
          "description": "21. 5 inches Full HD (1920 x 1080) widescreen IPS display And Radeon free Sync technology. No compatibility for VESA Mount Refresh Rate: 75Hz - Using HDMI port Zero-frame design | ultra-thin | 4ms response time | IPS panel Aspect ratio - 16: 9. Color Supported - 16. 7 million colors. Brightness - 250 nit Tilt angle -5 degree to 15 degree. Horizontal viewing angle-178 degree. Vertical viewing angle-178 degree 75 hertz",
          "category": "electronics",
          "image": "https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg",
          "rating":2.9,
          "count": 250
      },
      {
          "id": 14,
          "name": "Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED ",
          "price": 999.99,
          "description": "49 INCH SUPER ULTRAWidE 32:9 CURVED GAMING MONITOR with dual 27 inch screen side by side QUANTUM DOT (QLED) TECHNOLOGY, HDR support and factory calibration provides stunningly realistic and accurate color and contrast 144HZ HIGH REFRESH RATE and 1ms ultra fast response time work to eliminate motion blur, ghosting, and reduce input lag",
          "category": "electronics",
          "image": "https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg",
          "rating": 2.2,
          "count": 140
      },
      {
          "id": 15,
          "name": "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
          "price": 56.99,
          "description": "Note:The Jackets is US standard size, Please choose size as your usual wear Material: 100% Polyester; Detachable Liner Fabric: Warm Fleece. Detachable Functional Liner: Skin Friendly, Lightweigt and Warm.Stand Collar Liner jacket, keep you warm in cold weather. Zippered Pockets: 2 Zippered Hand Pockets, 2 Zippered Pockets on Chest (enough to keep cards or keys)and 1 Hidden Pocket Inside.Zippered Hand Pockets and Hidden Pocket keep your things secure. Humanized Design: Adjustable and Detachable Hood and Adjustable cuff to prevent the wind and water,for a comfortable fit. 3 in 1 Detachable Design provide more convenience, you can separate the coat and inner as needed, or wear it together. It is suitable for different season and help you adapt to different climates",
          "category": "women's clothing",
          "image": "https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg",
          "rating": 2.6,
          "count": 235
      },
      {
          "id": 16,
          "name": "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
          "price": 29.95,
          "description": "100% POLYURETHANE(shell) 100% POLYESTER(lining) 75% POLYESTER 25% COTTON (SWEATER), Faux leather material for style and comfort / 2 pockets of front, 2-For-One Hooded denim style faux leather jacket, Button detail on waist / Detail stitching at sides, HAND WASH ONLY / DO NOT BLEACH / LINE DRY / DO NOT IRON",
          "category": "women's clothing",
          "image": "https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg",
          "rating": 2.9,
          "count": 340
      },
      {
          "id": 17,
          "name": "Rain Jacket Women Windbreaker Striped Climbing Raincoats",
          "price": 39.99,
          "description": "Lightweight perfet for trip or casual wear---Long sleeve with hooded, adjustable drawstring waist design. Button and zipper front closure raincoat, fully stripes Lined and The Raincoat has 2 side pockets are a good size to hold all kinds of things, it covers the hips, and the hood is generous but doesn't overdo it.Attached Cotton Lined Hood with Adjustable Drawstrings give it a real styled look.",
          "category": "women's clothing",
          "image": "https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg",
          "rating":3.8,
          "count": 679
      },
      {
          "id": 18,
          "name": "MBJ Women's Solid Short Sleeve Boat Neck V ",
          "price": 9.85,
          "description": "95% RAYON 5% SPANDEX, Made in USA or Imported, Do Not Bleach, Lightweight fabric with great stretch for comfort, Ribbed on sleeves and neckline / Double stitching on bottom hem",
          "category": "women's clothing",
          "image": "https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg",
          "rating":4.7,
          "count": 130
      },
      {
          "id": 19,
          "name": "Opna Women's Short Sleeve Moisture",
          "price": 7.95,
          "description": "100% Polyester, Machine wash, 100% cationic polyester interlock, Machine Wash & Pre Shrunk for a Great Fit, Lightweight, roomy and highly breathable with moisture wicking fabric which helps to keep moisture away, Soft Lightweight Fabric with comfortable V-neck collar and a slimmer fit, delivers a sleek, more feminine silhouette and Added Comfort",
          "category": "women's clothing",
          "image": "https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg",
          "rating":4.5,
          "count": 146
      },
      {
          "id": 20,
          "name": "DANVOUY Womens T Shirt Casual Cotton Short",
          "price": 12.99,
          "description": "95%Cotton,5%Spandex, Features: Casual, Short Sleeve, Letter Print,V-Neck,Fashion Tees, The fabric is soft and has some stretch., Occasion: Casual/Office/Beach/School/Home/Street. Season: Spring,Summer,Autumn,Winter.",
          "category": "women's clothing",
          "image": "https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg",
          "rating": 3.6,
          "count": 145
      },
      
		{
			"id": "1",
			"name": "Banana",
			"category": "Groceries",
			"Subcategory": "Musaceae",
			"brand": "The banana company",
			"Contents": "Banana",
			"description": "The banana is an edible fruit, botanically a berry, produced by several kinds of large herbaceous flowering plants in the genus Musa. In some countries, bananas used for cooking may be called plantains. The fruit is variable in size, color and firmness, but is usually elongated and curved, with soft flesh rich in starch covered with a rind which may be green, yellow, red, purple, or brown when ripe. The fruits grow in clusters hanging from the top of the plant. Almost all modern edible parthenocarpic (seedless) bananas come from two wild species - Musa acuminata and Musa balbisiana. The scientific names of most cultivated bananas are Musa acuminata, Musa balbisiana, and Musa x paradisiaca for the hybrid Musa acuminata x M. balbisiana, depending on their genomic constitution. The old scientific name Musa sapientum is no longer used. It is also yellow.",
			"Organic": true,
			"image": "http://www.loop54.com/hubfs/demo_images/banana.jpg",
			"Orgprice": 7,
			"price": 7
		}, {
			"id": "2",
			"name": "Cinnamon roll",
			"category": "Groceries",
			"Subcategory": "Cookies and sweets",
			"brand": "Awesome bakery",
			"Contents": "Wheat flour,Cinnamon,Bunnies",
			"description": "A cinnamon roll (also cinnamon bun, cinnamon swirl, cinnamon Danish and cinnamon snail) is a sweet roll served commonly in Northern Europe and North America. In North America its common use is for breakfast. Its main ingredients are flour, cinnamon, sugar, and butter, which provide a robust and sweet flavor. In some places it is eaten as a breakfast food and is often served with cream cheese or icing.",
			"Organic": false,
			"image": "http://www.loop54.com/hubfs/demo_images/cinnamonroll.jpg",
			"Orgprice": 5,
			"price": 5
		}, {
			"id": "3",
			"name": "Apple",
			"category": "Groceries",
			"Subcategory": "Rosaceae",
			"brand": "Fruits n Veggies",
			"Contents": "Apple",
			"description": "The apple tree (Malus domestica) is a deciduous tree in the rose family best known for its sweet, pomaceous fruit, the apple. It is cultivated worldwide as a fruit tree, and is the most widely grown species in the genus Malus. The tree originated in Central Asia, where its wild ancestor, Malus sieversii, is still found today. Apples have been grown for thousands of years in Asia and Europe, and were brought to North America by European colonists. Apples have religious and mythological significance in many cultures, including Norse, Greek and European Christian traditions.",
			"Organic": false,
			"image": "http://www.loop54.com/hubfs/demo_images/apple.jpg",
			"Orgprice": 6,
			"price": 6
		}, {
			"id": "5",
			"name": "Milk",
			"category": "Groceries",
			"Subcategory": "Milk",
			"brand": "Early",
			"Contents": "Milk from cow",
			"description": "Milk is a white liquid produced by the mammary glands of mammals. It is the primary source of nutrition for young mammals before they are able to digest other types of food. Early-lactation milk contains colostrum, which carries the mother's antibodies to its young and can reduce the risk of many diseases. Milk contains many other nutrients and the carbohydrate lactose.",
			"Organic": false,
			"image": "http://www.loop54.com/hubfs/demo_images/milk.jpg",
			"Orgprice": 10,
			"price": 10
		}, {
			"id": "6",
			"name": "Organic Milk",
			"category": "Groceries",
			"Subcategory": "Milk",
			"brand": "Early",
			"Contents": "Milk from cow",
			"description": "Milk is a white liquid produced by the mammary glands of mammals. It is the primary source of nutrition for young mammals before they are able to digest other types of food. Early-lactation milk contains colostrum, which carries the mother's antibodies to its young and can reduce the risk of many diseases. Milk contains many other nutrients and the carbohydrate lactose.",
			"Organic": true,
			"image": "http://www.loop54.com/hubfs/demo_images/organicmilk.jpg",
			"Orgprice": 12,
			"price": 12
		}, {
			"id": "7",
			"name": "Organic Apple",
			"category": "Groceries",
			"Subcategory": "Rosaceae",
			"brand": "The banana company",
			"Contents": "Apple",
			"description": "The apple tree (Malus domestica) is a deciduous tree in the rose family best known for its sweet, pomaceous fruit, the apple. It is cultivated worldwide as a fruit tree, and is the most widely grown species in the genus Malus. The tree originated in Central Asia, where its wild ancestor, Malus sieversii, is still found today. Apples have been grown for thousands of years in Asia and Europe, and were brought to North America by European colonists. Apples have religious and mythological significance in many cultures, including Norse, Greek and European Christian traditions.",
			"Organic": true,
			"image": "http://www.loop54.com/hubfs/demo_images/greenapple.jpg",
			"Orgprice": 7,
			"price": 7
		}, {
			"id": "8",
			"name": "Ground beef",
			"category": "Groceries",
			"Subcategory": "Beef",
			"brand": "MeatNStuff",
			"Contents": "Ground beef",
			"description": "Ground beef, beef mince, minced meat, hamburger (in the United States) is a ground meat made of beef, finely chopped by a meat grinder. It is used in many recipes including hamburgers and cottage pie. In some parts of the world, a meat grinder is called a mincer.",
			"Organic": true,
			"image": "http://www.loop54.com/hubfs/demo_images/groundbeef.jpg",
			"Orgprice": 65,
			"price": 65
		}, {
			"id": "9",
			"name": "Steak",
			"category": "Groceries",
			"Subcategory": "Beef",
			"brand": "UltraBovine",
			"Contents": "Beef",
			"description": "A steak is a meat generally sliced perpendicular to the muscle fibers, potentially including a bone. Exceptions, in which the meat is sliced parallel to the fibers, include the skirt steak that is cut from the plate, the flank steak that is cut from the abdominal muscles, and the Silverfinger steak that is cut from the loin and includes three rib bones. When the word \"steak\" is used without qualification, it generally refers to a beef steak. In a larger sense, there are also fish steaks, ground meat steaks, pork steak and many more varieties.",
			"Organic": true,
			"image": "http://www.loop54.com/hubfs/demo_images/steak.jpg",
			"Orgprice": 100,
			"price": 100
		}, {
			"id": "10",
			"name": "Chicken breast",
			"category": "Groceries",
			"Subcategory": "Bird",
			"brand": "MeatNStuff",
			"Contents": "Meat from chicken",
			"description": "Chicken is the most common type of poultry in the world. In developed countries, chickens are usually subject to intensive farming methods.",
			"Organic": false,
			"image": "http://www.loop54.com/hubfs/demo_images/chickenbreast.jpg",
			"Orgprice": 55,
			"price": 55
		}, {
			"id": "11",
			"name": "Organic Chicken breast",
			"category": "Groceries",
			"Subcategory": "Bird",
			"brand": "Happy birds",
			"Contents": "Meat from chicken",
			"description": "Chicken is the most common type of poultry in the world. In developed countries, chickens are usually subject to intensive farming methods.",
			"Organic": true,
			"image": "http://www.loop54.com/hubfs/demo_images/organicchickenbreast.jpg",
			"Orgprice": 65,
			"price": 55,
			"Campaigns":["Sale", "Organic sale"]
		}, {
			"id": "12",
			"name": "Whole chicken",
			"category": "Groceries",
			"Subcategory": "Bird",
			"brand": "MeatNStuff",
			"Contents": "Meat from chicken",
			"description": "Chicken is the most common type of poultry in the world. In developed countries, chickens are usually subject to intensive farming methods.",
			"Organic": false,
			"image": "http://www.loop54.com/hubfs/demo_images/wholechicken.jpg",
			"Orgprice": 40,
			"price": 40
		}, {
			"id": "13",
			"name": "Wheat flour",
			"category": "Groceries",
			"Subcategory": "Flours",
			"brand": "Grinders inc",
			"Contents": "Ground wheat",
			"description": "Wheat flour is a powder made from the grinding of wheat used for human consumption. More wheat flour is produced than any other flour. Wheat varieties are called \"soft\" or \"weak\" if gluten content is low, and are called \"hard\" or \"strong\" if they have high gluten content. Hard flour, or bread flour, is high in gluten, with 12% to 14% gluten content, its dough has elastic toughness that holds its shape well once baked. Soft flour is comparatively low in gluten and thus results in a loaf with a finer, crumbly texture. Soft flour is usually divided into cake flour, which is the lowest in gluten, and pastry flour, which has slightly more gluten than cake flour.",
			"Organic": false,
			"image": "http://www.loop54.com/hubfs/demo_images/flour.jpg",
			"Orgprice": 12,
			"price": 12
		}, {
			"id": "14",
			"name": "Powdered sugar",
			"category": "Groceries",
			"Subcategory": "Sugar",
			"brand": "Sweet Home Alabama",
			"Contents": "Ground sugar from sugar cane",
			"description": "Sugar is the generalized name for sweet, short-chain, soluble carbohydrates, many of which are used in food. They are carbohydrates, composed of carbon, hydrogen, and oxygen. There are various types of sugar derived from different sources. Simple sugars are called monosaccharides and include glucose (also known as dextrose), fructose and galactose. The table or granulated sugar most customarily used as food is sucrose, a disaccharide. (In the body, sucrose hydrolyses into fructose and glucose.) Other disaccharides include maltose and lactose. Longer chains of sugars are called oligosaccharides. Chemically-different substances may also have a sweet taste, but are not classified as sugars. Some are used as lower-calorie food substitutes for sugar described as artificial sweeteners.",
			"Organic": false,
			"image": "http://www.loop54.com/hubfs/demo_images/powderedsugar.jpg",
			"Orgprice": 11,
			"price": 11,
			"IsNew": true
		}, {
			"id": "15",
			"name": "Organic Sugar",
			"category": "Groceries",
			"Subcategory": "Sugar",
			"brand": "Sweet Home Alabama",
			"Contents": "Sugar from sugar cane",
			"description": "Sugar is the generalized name for sweet, short-chain, soluble carbohydrates, many of which are used in food. They are carbohydrates, composed of carbon, hydrogen, and oxygen. There are various types of sugar derived from different sources. Simple sugars are called monosaccharides and include glucose (also known as dextrose), fructose and galactose. The table or granulated sugar most customarily used as food is sucrose, a disaccharide. (In the body, sucrose hydrolyses into fructose and glucose.) Other disaccharides include maltose and lactose. Longer chains of sugars are called oligosaccharides. Chemically-different substances may also have a sweet taste, but are not classified as sugars. Some are used as lower-calorie food substitutes for sugar described as artificial sweeteners.",
			"Organic": true,
			"image": "http://www.loop54.com/hubfs/demo_images/sugar.jpg",
			"Orgprice": 14,
			"price": 14
		}, {
			"id": "16",
			"name": "Oatmeal",
			"category": "Groceries",
			"Subcategory": "Grains",
			"brand": "Grinders inc",
			"Contents": "Ground oats",
			"description": "Oatmeal is oat groats (i.e. grains) that have been ground, steel-cut, crushed, or rolled. Ground oats are also called 'white oats'. The term 'oatmeal' is also used in the U.S. and parts of Canada to mean oat porridge.",
			"Organic": false,
			"image": "http://www.loop54.com/hubfs/demo_images/oatmeal.jpg",
			"Orgprice": 12,
			"price": 12
		}, {
			"id": "17",
			"name": "Orange",
			"category": "Groceries",
			"Subcategory": "Citrus",
			"brand": "Fruits n Veggies",
			"Contents": "Orange",
			"description": "The orange (specifically, the sweet orange) is the fruit of the citrus species Citrus x sinensis in the family Rutaceae.",
			"Organic": false,
			"image": "http://www.loop54.com/hubfs/demo_images/orange.jpg",
			"Orgprice": 5,
			"price": 5
		}, {
			"id": "18",
			"name": "Yoghurt",
			"category": "Groceries",
			"Subcategory": "Yoghurt",
			"brand": "Early",
			"Contents": "Sour milk with bacteria",
			"description": "Yogurt, yoghurt, or yoghourt (from Turkish: yogurt; other spellings listed below) is a food produced by bacterial fermentation of milk. The bacteria used to make yogurt are known as \"yogurt cultures\". Fermentation of lactose by these bacteria produces lactic acid, which acts on milk protein to give yogurt its texture and characteristic tang. Worldwide, cow's milk, the protein of which is mainly casein, is most commonly used to make yogurt. Milk from water buffalo, goats, ewes, mares, camels, and yaks, however, is also used to produce yogurt in various parts of the world.",
			"Organic": false,
			"image": "http://www.loop54.com/hubfs/demo_images/yoghurt.jpg",
			"Orgprice": 14,
			"price": 14
		}, {
			"id": "19",
			"name": "Syrup",
			"category": "Groceries",
			"Subcategory": "Sugar",
			"brand": "Sweet Home Alabama",
			"Contents": "Syrup",
			"description": "In cooking, a syrup or sirup is a condiment that is a thick, viscous liquid consisting primarily of a solution of sugar in water, containing a large amount of dissolved sugars but showing little tendency to deposit crystals. Its consistency is similar to that of molasses. The viscosity arises from the multiple hydrogen bonds between the dissolved sugar, which has many hydroxyl (OH) groups, and the water. The most popular brand of syrup in the United States, Aunt Jemima, has been prominent in pop culture, with one episode of the tv show South Park giving it a key role.",
			"Organic": false,
			"image": "http://www.loop54.com/hubfs/demo_images/syrup.jpg",
			"Orgprice": 24,
			"price": 24
		}, {
			"id": "20",
			"name": "Maple Syrup",
			"category": "Groceries",
			"Subcategory": "Sugar",
			"brand": "Ootstanding, Ey?",
			"Contents": "Syrup",
			"description": "Maple syrup is a syrup usually made from the xylem sap of sugar maple, red maple, or black maple trees, although it can also be made from other maple species. In cold climates, these trees store starch in their trunks and roots before the winter; the starch is then converted to sugar that rises in the sap in the spring. Maple trees can be tapped by boring holes into their trunks and collecting the exuded sap. The sap is processed by heating to evaporate much of the water, leaving the concentrated syrup.",
			"Organic": true,
			"image": "http://www.loop54.com/hubfs/demo_images/maplesyrup.jpg",
			"Orgprice": 34,
			"price": 34
		}, {
			"id": "21",
			"name": "Coffee",
			"category": "Groceries",
			"Subcategory": "Coffe and Tea",
			"brand": "Dipton",
			"Contents": "Ground coffee",
			"description": "Coffee is a brewed drink prepared from roasted coffee beans, which are the seeds of berries from the Coffea plant. Coffee plants are cultivated in over 70 countries, primarily in the equatorial regions of the Americas, Southeast Asia, India and Africa. The two most commonly grown are the highly regarded arabica, and the less sophisticated but stronger and more hardy robusta. The latter is resistant to the coffee leaf rust, Hemileia vastatrix, but has a more bitter taste. Once ripe, coffee beans are picked, processed, and dried. Green (unroasted) coffee beans are one of the most traded agricultural commodities in the world. Once traded, the beans are roasted to varying degrees, depending on the desired flavor, before being ground and brewed to create coffee.",
			"Organic": false,
			"image": "http://www.loop54.com/hubfs/demo_images/coffee.jpg",
			"Campaigns":["Sale"],
			"Orgprice": 46,
			"price": 36
		}, {
			"id": "22",
			"name": "Mutton steak",
			"category": "Groceries",
			"Subcategory": "Mutton",
			"brand": "MeatNStuff",
			"Contents": "Meat from lamb",
			"description": "Lamb, hogget, and mutton (UK, India, South Africa, Canada, New Zealand and Australia) are terms for the meat of domestic sheep (species Ovis aries) at different ages.",
			"Organic": true,
			"image": "http://www.loop54.com/hubfs/demo_images/mutton.jpg",
			"Orgprice": 76,
			"price": 76
		}, {
			"id": "23",
			"name": "Beer",
			"category": "Groceries",
			"Subcategory": "Drinks",
			"brand": "Charles Mountain",
			"Contents": "Malt, hops, yeast and water",
			"description": "Beer is an alcoholic beverage produced by the saccharification of starch and fermentation of the resulting sugar. The starch and saccharification enzymes are often derived from malted cereal grains, most commonly malted barley and malted wheat. Most beer is also flavoured with hops, which add bitterness and act as a natural preservative, though other flavourings such as herbs or fruit may occasionally be included. The brewing process causes a natural carbonation effect, although forced carbonation is also used. The preparation of beer is called brewing.",
			"Organic": false,
			"image": "http://www.loop54.com/hubfs/demo_images/beer.jpg",
			"Orgprice": 16,
			"price": 16
		}, {
			"id": "24",
			"name": "Organic Beer",
			"category": "Groceries",
			"Subcategory": "Drinks",
			"brand": "Charles Mountain",
			"Contents": "Malt, hops, yeast and water",
			"description": "Beer is an alcoholic beverage produced by the saccharification of starch and fermentation of the resulting sugar. The starch and saccharification enzymes are often derived from malted cereal grains, most commonly malted barley and malted wheat. Most beer is also flavoured with hops, which add bitterness and act as a natural preservative, though other flavourings such as herbs or fruit may occasionally be included. The brewing process causes a natural carbonation effect, although forced carbonation is also used. The preparation of beer is called brewing.",
			"Organic": true,
			"image": "http://www.loop54.com/hubfs/demo_images/organicbeer.jpg",
			"Orgprice": 19,
			"price": 19,
		}
	
  
  ],
};
export default data;
